### ISSUE TITLE
Commitments

### ISSUE THREAD

**Issue by andylolz** [pwyf/2018-technical-consultation#12]
## Description

The overall financial cost or amount is a summary total financial sum for the activity.

This is only expected if the activity is in the implementation, completion or post-completion phase.

### IATI 2.0x

```python
For each current activity,
i​f `activity-status/@code` is one of (2, 3, 4)
then `transaction/transaction-type[@code="2"]` should be present
```

### IATI 1.0x

```python
For each current activity,
i​f `activity-status/@code` is one of (2, 3, 4)
then `transaction/transaction-type[@code="C"]` should be present
```

**Comment by breidertmt** [comment]
Are there any dependencies in this field or have they been dropped? I believe in the past you failed conditions if you did not have a proper title..... Which I do not supporrt. Just want to be clear.

**Comment by abdulriza** [comment]
Proposed test for IATI 2.0X should check either code 2 or 11 to accommodate incoming commitment introduced in IATI 2.0X. Therefore, the test should read as;

i​f `activity-status/@code` is one of (2, 3, 4)
then `transaction/transaction-type[@code="2"]` should be present
or `transaction/transaction-type[@code="11"]` should be present

**Comment by francescafo** [comment]
Can you please clarify if the commitment can only refer to level 1 commitments when published data is hierarchical (2 levels)? thank you

**Comment by andylolz** [comment]
> Proposed test for IATI 2.0X should check either code 2 or 11 to accommodate incoming commitment introduced in IATI 2.0X.

@abdulriza: This indicator is specifically about outgoing commitments, so I don’t think Transaction Type 11 (incoming commitments) should be included. We plan to update the description of this indicator to be more explicit about this.

**Comment by andylolz** [comment]
> Can you please clarify if the commitment can only refer to level 1 commitments when published data is hierarchical (2 levels)?

@francescafo: If hierarchies are used, then commitments and other financial transaction data should only be expected at the lowest level (in line with IATI guidelines).

**Comment by andylolz** [comment]
> Are there any dependencies in this field or have they been dropped? I believe in the past you failed conditions if you did not have a proper title..... Which I do not supporrt. Just want to be clear.

@breidertmt: Thanks for raising this, and apologies for the delayed response. You’re describing the sampling process, which also needs to be discussed. Do you mind if we revisit that? It’s currently under discussion.

**Comment by abdulriza** [comment]
@andylolz I don't think it should be only about outgoing commitment. You will not have outgoing commitments when you are the implementing organization. Therefore, if you are looking for outgoing  commitment only then the test should first define whether the activity is subject to outgoing commitments by checking if the publisher is the implementing organization or not. In my opinion, incoming commitment is important as much as the outgoing commitment and therefore, the test should simply look for either of it.

**Comment by AndieVaughn** [comment]
We realized that to pass this test, nothing must be blank and we must have a 0 in the field.  When obligations or disbursements fall outside of the test year, if there is no 0 in the file, then there is a penalty.  We recommend combining Disbursement and Commitment to measure if there is a commitment OR a disbursement into 1 test so that this issue is resolved.

**Comment by abdulriza** [comment]
@AndieVaughn I don't think the commitment is relevant to the test year. Commitment is 'a firm, written obligation from a donor or provider to provide a specified amount of funds, under particular terms and conditions, for specific purposes, for the benefit of the recipient'. Since we don't need to publish yearly commitment, I don't think there will be any issue of 'fall outside of the year' as long as the total commitment is published for the activity.

**Comment by AndieVaughn** [comment]
Thanks, @abdulriza  - the year is relevant to the test for our data. To clarify, we are talking about outgoing commitments from a donor. For example, 20% of our activities fail this test because they do not have a commitment in that year, but there is a disbursement.  If there is no commitment reported, it fails the test even though we are accurately reporting the transactions.  Our suggestion is to combine the disbursement and commitment measure into 1 test so this issue is resolved and we don't need to add extraneous zero transactions to pass this test.  Does that make sense?

**Comment by ToonVB** [comment]
We agree with @francescafo : in the case of hierarchically structured data, commitments should be indicated at the highest level, since the "firm, written obligation " regards the whole, while disbursements/expenditures should indeed only be indicated at the lowest level, in order to avoid double-counting, as the IATI guidelines justly mention.
This is rather important for us, since we try to give as much (indicative) details as possible, as to for which locations and sector the underlying "children" activities are relevant.
We'll take this to the IATI discuss pages to try and get feedback/clarification.

**Comment by abdulriza** [comment]
@AndieVaughn Thanks for the clarification. But I still don't understand why you refer to as 'do not have a commitment **in that year**'. The test simply looks for commitment in the activity and the commitment doesn't have to be in the current year. The activity fails this test if there is no commitment published(as long as activity status is 2, 3, 4). My point is as long as you have published the commitment agreed with the  receiving organization (for those who you disburse the money), which I believe become available before the disbursement, those 20% of your activities will not fail the test. May be I am missing a point in how it works in your organization but in general the commitment should be available for any donor projects with the status 2, 3, or 4. I don't agree with combining commitment and disbursement as you know disbursement is part of money spent (with expenditure).

**Comment by AndieVaughn** [comment]
@abdulriza - That makes sense.  We thought it looked only for the last 12 months, but now see you are correct.  We are okay with this test now.

We put the same comment here as on the disbursements tab, but do standby our comment on disbursements that those do not necessarily exist though there was a commitment.  A current activity with a commitment doesn't necessarily have a disbursement attached to it.

**Comment by johnadamsDFID** [comment]
Toon,  commitments can be expressed at lower levels in the hierarchy too - for example representing a purchase order with a particular provider. 

The flexible thing would be for the organisation to detail which elements are within which hierarchy.

**Comment by andylolz** [comment]
@abdulriza: we’ll follow up directly regarding activities where UNDP is the implementing organisation.

**Comment by andylolz** [comment]
Thanks for the comments here.

We’ll modify this test to check that at least one non-zero value commitment is present.

We’ll also modify the description to make it clear this test is about outgoing commitments.
